# Generated by Django 5.0.6 on 2024-07-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisAcelerometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_x', models.FloatField()),
                ('promedio_y', models.FloatField()),
                ('promedio_z', models.FloatField()),
                ('mediana_x', models.FloatField()),
                ('mediana_y', models.FloatField()),
                ('mediana_z', models.FloatField()),
                ('maximo_x', models.FloatField()),
                ('maximo_y', models.FloatField()),
                ('maximo_z', models.FloatField()),
                ('minimo_x', models.FloatField()),
                ('minimo_y', models.FloatField()),
                ('minimo_z', models.FloatField()),
                ('tiempo_inicial', models.DateTimeField()),
                ('tasa_muestreo', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4data.usuario')),
            ],
        ),
    ]
