# Generated by Django 5.0.6 on 2024-07-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0002_analisisacelerometro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisisacelerometro',
            old_name='tiempo_inicial',
            new_name='inicio_sesion',
        ),
    ]
