# Generated by Django 5.0.7 on 2024-08-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0003_rename_tiempo_inicial_analisisacelerometro_inicio_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisacelerometro',
            name='inicio_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisisacelerometro',
            name='tasa_muestreo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnalisisBVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('mediana', models.FloatField()),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('inicio_sesion', models.DateTimeField(blank=True, null=True)),
                ('tasa_muestreo', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4data.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalisisIBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('mediana', models.FloatField()),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('inicio_sesion', models.DateTimeField(blank=True, null=True)),
                ('tasa_muestreo', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4data.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
