# Generated by Django 5.0.7 on 2024-08-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e4data', '0004_alter_analisisacelerometro_inicio_sesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisEDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('mediana', models.FloatField()),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('inicio_sesion', models.DateTimeField(blank=True, null=True)),
                ('tasa_muestreo', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e4data.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
